AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  vulcan

  Sample SAM Template for vulcan

Parameters:
  InvincibleUrl:
    Type: String
    Description: InvincibleUrl service URL

  KairosQueueUrl:
    Type: String
    Description: Kairos Queue Url

  SQSExecutionRoleArn:
    Type: String
    Description: SQS Execution Role Arn

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  AssignPagesToRawPostsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: assignPageToRawPosts.lambdaHandler
      Role: !Ref SQSExecutionRoleArn
      Runtime: nodejs18.x
      MemorySize: 1024
      Architectures:
        - x86_64
      Environment:
        Variables:
          InvincibleUrl: !Ref InvincibleUrl
          KairosQueueUrl: !Ref KairosQueueUrl
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - functions/assignPageToRawPosts.ts
# Outputs:
# ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
# Find out more about other implicit resources you can reference within SAM
# https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
